kind: pipeline
name: sonar-test

workspace:
  base: /build

steps:
  - name: sonarqube
    image: newtmitch/sonar-scanner
    secrets:
      - source: sonar_token
        target: SONAR_TOKEN
    volumes:
      - name: sonar-cache
        path: sonar-cache:/root/.sonar/cache
    commands:
      - >
        sonar-scanner
        -Dsonar.projectName=${DRONE_REPO}
        -Dsonar.host.url=https://sonarhub.serveo.net
        -Dsonar.projectKey=api-gateway:${DRONE_BRANCH}
        -Dsonar.projectVersion=${DRONE_COMMIT}
        -Dsonar.projectBaseDir=.

trigger:
  branch:
    exclude:
      - master

kind: pipeline
name: build-image

workspace:
  base: /build

steps:
  - name: build-image
    image: alpine
    commands:
      - pwd
      - ls
      - ls -R
