---
kind: pipeline
name: sonar-test

workspace:
  base: /build

steps:
  - name: sonar-test
    image: newtmitch/sonar-scanner
    environment:
      SONAR_TOKEN:
        from_secret: sonar-token
    commands:
      - sonar-scanner \
        -Dsonar.host.url=http://sonarhub.serveo.net \
        -Dsonar.projectName="${DRONE_REPO}" \
        -Dsonar.projectKey=api-gateway:${DRONE_BRANCH} \
        -Dsonar.projectVersion=${DRONE_COMMIT} \
        -Dsonar.login=$SONAR_TOKEN \
        -Dsonar.projectBaseDir=. \
        -Dsonar.sources=.

---
kind: pipeline
name: build-image

workspace:
  base: /build

steps:
  - name: build-image
    image: golang:1.12-alpine3.9
    commands:
      - pwd
      - ls
      - ls -R
